name: Environment Variables Action
description: Fetch environment variables without creating deployments.
author: YUMEMI Inc.
branding:
  icon: box
  color: blue
runs:
  using: node20
  main: 'index.js'
inputs:
  environment:
    required: true
    description: Name of the environment to fetch variables from.
  token:
    required: true
    description: |
      GitHub token with actions:read access.
      Required since github.token does not support environments:read scope.
  repository_id:
    required: true
    description: Unique identifier of the repository.
    default: '${{ github.repository_id }}'
  export:
    required: true
    description: Export the variables to GITHUB_ENV.
    default: 'false'
